# Generated by Django 5.2.8 on 2025-12-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_qualifying',
            field=models.BooleanField(default=False),
        ),
    ]
