# Generated by Django 6.0 on 2025-12-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_purchase_is_qualifying'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorprofile',
            name='completed_groups',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
