# Generated by Django 6.0 on 2025-12-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_ambassadorprofile_completed_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='ambassador_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
