# Generated by Django 5.2.8 on 2025-11-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_emailotp_order_address_order_city_order_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, default='Enter City', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(blank=True, default='Enter Country', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fullname',
            field=models.CharField(blank=True, default='Enter Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, default='Enter Phone Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(blank=True, default='Enter State', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_street',
            field=models.CharField(blank=True, default='Enter Street Address', max_length=255, null=True),
        ),
    ]
