# Generated by Django 5.2.8 on 2025-11-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_address_remove_order_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='created_at',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
