# Generated by Django 5.2.8 on 2025-11-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_emailotp_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='is_verified',
        ),
    ]
