# Generated by Django 5.2.8 on 2025-11-29 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='demo_video',
            field=models.FileField(blank=True, null=True, upload_to='demo_videos/'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
