# Generated by Django 5.2.8 on 2025-12-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productimage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_qualifying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='network_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='referrer_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
