# Generated by Django 6.0 on 2025-12-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_is_qualifying_order_network_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_qualifying',
            field=models.BooleanField(default=False),
        ),
    ]
