# Generated by Django 6.0 on 2025-12-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_ambassador',
            field=models.BooleanField(default=False),
        ),
    ]
