# Generated by Django 6.0 on 2025-12-27 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital_category',
            field=models.CharField(blank=True, choices=[('ebook', 'Ebook'), ('ecourse', 'Ecourse'), ('cac', 'CAC'), ('pos', 'POS')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital')], default='physical', max_length=20),
        ),
        migrations.CreateModel(
            name='DigitalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('requirements', models.TextField(blank=True)),
                ('payment_proof', models.ImageField(upload_to='payment_proofs/digital/')),
                ('fulfillment_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(limit_choices_to={'product_type': 'digital'}, on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
    ]
