# Generated by Django 6.0 on 2025-12-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_product_digital_category_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalorder',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/id_cards/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='nin',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/nins/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='signature_director',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/signatures/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='signature_witness',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/signatures/'),
        ),
    ]
