# Generated by Django 6.0 on 2025-12-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_digitalorder_id_card_digitalorder_nin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='digital_category',
            field=models.CharField(blank=True, choices=[('ebook', 'Ebook'), ('ecourse', 'Ecourse'), ('cac', 'CAC'), ('pos', 'POS'), ('ngo', 'NGO'), ('business name', 'Business Name')], max_length=20, null=True),
        ),
    ]
