# Generated by Django 6.0 on 2025-12-31 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_product_digital_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalorder',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='digitalorder',
            name='fulfillment_link',
        ),
        migrations.RemoveField(
            model_name='digitalorder',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='digitalorder',
            name='nin',
        ),
        migrations.RemoveField(
            model_name='digitalorder',
            name='signature_director',
        ),
        migrations.RemoveField(
            model_name='digitalorder',
            name='signature_witness',
        ),
        migrations.AlterField(
            model_name='digitalorder',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/digital/'),
        ),
        migrations.AlterField(
            model_name='digitalorder',
            name='requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='digitalorder',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DigitalOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='digital_orders/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='store.digitalorder')),
            ],
        ),
    ]
