# Generated by Django 6.0 on 2025-12-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_digitalorder_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalorder',
            name='fulfillment_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
