# Generated by Django 6.0 on 2025-12-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_digitalorder_fulfillment_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalorder',
            name='fulfillment_link',
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/id_cards/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='nin',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/nins/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='signature_director',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/signatures/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='signature_witness',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/signatures/'),
        ),
        migrations.AlterField(
            model_name='digitalorder',
            name='payment_proof',
            field=models.ImageField(upload_to='payment_proofs/digital/'),
        ),
        migrations.AlterField(
            model_name='digitalorder',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='digitalorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='DigitalOrderFile',
        ),
    ]
