# Generated by Django 6.0 on 2025-12-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_digitalorder_fulfillment_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalorder',
            name='chairman_nin_slip',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/ngo/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='chairman_photo',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/ngo/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='chairman_signature',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/ngo/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='identification_file',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/pos/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/business_name/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='passport_photo',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/pos/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='secretary_nin_slip',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/ngo/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='secretary_photo',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/ngo/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='secretary_signature',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/ngo/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/business_name/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='signature_file',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/pos/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee1_nin_slip',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/ngo/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee1_photo',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/ngo/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee1_signature',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/ngo/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee2_nin_slip',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/ngo/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee2_photo',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/ngo/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee2_signature',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/ngo/'),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='utility_bill',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/pos/'),
        ),
        migrations.AlterField(
            model_name='digitalorder',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/business_name/'),
        ),
        migrations.AlterField(
            model_name='digitalorder',
            name='nin',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/cac/'),
        ),
        migrations.AlterField(
            model_name='digitalorder',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/digital/'),
        ),
        migrations.AlterField(
            model_name='digitalorder',
            name='signature_director',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/cac/'),
        ),
        migrations.AlterField(
            model_name='digitalorder',
            name='signature_witness',
            field=models.FileField(blank=True, null=True, upload_to='digital_orders/cac/'),
        ),
    ]
