# Generated by Django 6.0 on 2025-12-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_digitalorder_chairman_nin_slip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalorder',
            old_name='requirements',
            new_name='address',
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='business_address_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='business_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='business_house',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='business_lga',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='business_name1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='business_name2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='business_name_pos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='business_state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='business_street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='bvn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='chairman_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='chairman_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='chairman_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='chairman_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='chairman_nin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='chairman_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='company_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='company_house',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='company_lga',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='company_state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='company_street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='employment_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='firstname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='functional_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='home_address_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='home_address_pos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='home_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='home_house',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='home_lga',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='home_state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='home_street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='lga',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='lga_of_origin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='nature_of_business',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='nature_of_business_pos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='next_of_kin_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='next_of_kin_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='next_of_kin_country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='next_of_kin_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='next_of_kin_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='next_of_kin_lga',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='ngo_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='ngo_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='ngo_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='object1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='object2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='object3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='object4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='othername',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='phone_business',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='proposed_ngo_name1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='proposed_ngo_name2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='proposed_ngo_name3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='secretary_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='secretary_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='secretary_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='secretary_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='secretary_nin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='secretary_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='surname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee1_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee1_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee1_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee1_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee1_nin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee1_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee2_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee2_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee2_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee2_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee2_nin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustee2_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='trustees_tenure',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='witness_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='witness_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='witness_firstname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='witness_gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='witness_house',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='witness_lga',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='witness_othername',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='witness_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='witness_state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='witness_street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='digitalorder',
            name='witness_surname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
