# Generated by Django 6.0 on 2025-12-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('unpaid', 'Unpaid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('paid', 'Paid'), ('unpaid', 'Unpaid')], default='pending', max_length=20),
        ),
    ]
